#pragma once

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <string>

// Include the file generated by train_fusion_mlp.py.
// If the file doesn't exist yet, define a stub so the project still compiles.
#if __has_include("fusion/learned_fusion_corrector_weights.hpp")
#include "fusion/learned_fusion_corrector_weights.hpp"
#else
namespace rk3588::modules {
struct FusionMLPWeights {
    static constexpr int kInputDim = 9;
    static constexpr float kFeatMean[9] = {};
    static constexpr float kFeatStd[9] = {1, 1, 1, 1, 1, 1, 1, 1, 1};
    static constexpr float kFc1Weight[32][9] = {};
    static constexpr float kFc1Bias[32] = {};
    static constexpr float kFc2Weight[16][32] = {};
    static constexpr float kFc2Bias[16] = {};
    static constexpr float kFc3Weight[1][16] = {};
    static constexpr float kFc3Bias[1] = {};
};
}
#define RK3588_FUSION_MLP_STUB
#endif

#include "fusion/detection_distance_fusion.hpp"
#include "fusion/sensor_fusion.hpp"
#include "infer/rknn_runner.hpp"

namespace rk3588::modules {

struct LearnedFusionConfig {
    bool enabled = false;
    float min_cluster_score = 1.0f;
    int min_candidate_points = 4;
    float blend_weight = 0.50f;
    float min_distance_m = 0.30f;
    float max_correction_ratio = 0.30f;
};

class LearnedFusionCorrector {
public:
    explicit LearnedFusionCorrector(const SensorFusion& fusion,
                                     LearnedFusionConfig cfg = {})
        : fusion_(fusion), cfg_(cfg) {}

    void correct(std::vector<YoloDetection>* detections,
                 const std::vector<DistanceFusionDiagnostics>* diagnostics) {
        (void)detections;
        (void)diagnostics;
        if (!cfg_.enabled) return;
#ifdef RK3588_FUSION_MLP_STUB
        return;
#else
        if (detections == nullptr || diagnostics == nullptr) return;

        const int iw = std::max(1, fusion_.imageWidth());

        for (std::size_t i = 0; i < detections->size() && i < diagnostics->size(); ++i) {
            auto& det = (*detections)[i];
            const auto& diag = (*diagnostics)[i];

            if (det.distance_m < cfg_.min_distance_m) continue;
            if (diag.rejected_by_sanity) continue;

            const auto features_arr = buildFeatures(det, diag, iw);
            const float mlp_distance = mlpFusionPredict(features_arr.data());

            const bool gate_pass = (diag.cluster_score >= cfg_.min_cluster_score &&
                                    diag.cluster_points >= cfg_.min_candidate_points &&
                                    !diag.used_fallback);

            if (gate_pass) {
                const float trad = det.distance_m;
                const float blended = cfg_.blend_weight * mlp_distance +
                                      (1.0f - cfg_.blend_weight) * trad;
                det.distance_m = clampCorrection(blended, trad);
            } else if (diag.used_fallback && diag.candidate_points < 2) {
                det.distance_m = clampCorrection(mlp_distance, det.distance_m);
            }
        }
#endif  // RK3588_FUSION_MLP_STUB
    }

    const LearnedFusionConfig& config() const { return cfg_; }

private:
    std::array<float, 9> buildFeatures(const YoloDetection& det,
                         const DistanceFusionDiagnostics& diag,
                         int iw) const {
        const float center_x = 0.5f * static_cast<float>(det.left + det.right);
        const float center_y = 0.5f * static_cast<float>(det.top + det.bottom);
        const float box_w = static_cast<float>(std::max(0, det.right - det.left));
        const float box_h = static_cast<float>(std::max(0, det.bottom - det.top));
        const float iwf = static_cast<float>(iw);

        // Feature order must match extract_fusion_training_data.py
        return {
            center_x / iwf,
            center_y / iwf,
            box_w / iwf,
            box_h / iwf,
            (box_w * box_h) / (iwf * iwf),
            det.confidence,
            diag.raw_distance_m >= 0.0f ? diag.raw_distance_m : det.distance_m,
            static_cast<float>(diag.candidate_points),
            diag.cluster_score,
        };
    }

    float clampCorrection(float corrected, float original) const {
        const float max_delta = original * cfg_.max_correction_ratio;
        if (corrected > original + max_delta) return original + max_delta;
        if (corrected < original - max_delta) return original - max_delta;
        return std::max(0.0f, corrected);
    }

    const SensorFusion& fusion_;
    LearnedFusionConfig cfg_;
};

}  // namespace rk3588::modules
